aws_region         = "us-east-1"
project_name       = "devsecops-pipeline"
environment        = "production"
vpc_cidr           = "10.1.0.0/16"
availability_zones = ["us-east-1a", "us-east-1b", "us-east-1c"]
container_image    = "devsecops-pipeline-app:latest"
container_port     = 8080
task_cpu           = 512
task_memory        = 1024
desired_count      = 3
db_instance_class  = "db.t3.small"
db_name            = "appdb"
