soft-fail: false
compact: true
framework:
  - terraform
  - dockerfile
  - kubernetes
directory:
  - .
external-checks-dir:
  - policies/checkov
skip-check:
  - CKV_TF_1     # Module source not using commit hash (local modules)
  - CKV_TF_2     # Module source not using tag (local modules)
  - CKV_AWS_260  # ALB SG allows ingress on port 80 (intentional — HTTP→HTTPS redirect)
  - CKV_AWS_382  # SG allows all egress (standard pattern for ECS tasks)
  - CKV_AWS_23   # SG rule description — descriptions set on ingress blocks
  - CKV_AWS_158  # CloudWatch KMS encryption (AWS managed encryption sufficient for non-PII logs)
  - CKV_AWS_338  # CloudWatch 1-year retention (14 days is cost-effective for app logs, not audit)
  - CKV_AWS_136  # ECR KMS encryption (AES256 server-side encryption is enabled)
  - CKV_AWS_119  # DynamoDB KMS CMK (AWS managed encryption sufficient for state lock table)
