soft-fail: false
compact: true
framework:
  - terraform
  - dockerfile
  - kubernetes
directory:
  - .
external-checks-dir:
  - policies/checkov
skip-check:
  # --- Local modules ---
  - CKV_TF_1     # Module source not using commit hash (local modules)
  - CKV_TF_2     # Module source not using tag (local modules)
  # --- Networking (intentional for public-facing ALB) ---
  - CKV_AWS_260  # ALB SG allows ingress on port 80 (HTTP→HTTPS redirect)
  - CKV_AWS_382  # SG allows all egress (standard for ECS tasks needing ECR/S3/logs)
  - CKV_AWS_23   # SG rule description (descriptions on ingress blocks, not egress)
  - CKV_AWS_130  # Public subnets assign public IPs (required for ALB placement)
  - CKV_AWS_378  # ALB HTTP listener (intentional redirect-to-HTTPS listener)
  - CKV2_AWS_12  # VPC default SG (managed outside Terraform, not in scope)
  - CKV2_AWS_28  # ALB WAF association (WAF planned for production, omitted for scope)
  # --- Encryption: AWS managed sufficient, KMS CMK adds cost ---
  - CKV_AWS_158  # CloudWatch Log Group KMS
  - CKV_AWS_136  # ECR repository KMS (AES256 enabled)
  - CKV_AWS_119  # DynamoDB KMS CMK
  - CKV_AWS_354  # RDS Performance Insights KMS CMK
  # --- Retention & monitoring trade-offs ---
  - CKV_AWS_338  # CloudWatch 1-year retention (14d for app logs; audit logs separate)
  - CKV_AWS_118  # RDS enhanced monitoring (adds cost; CloudWatch metrics sufficient)
  # --- ALB & S3 access logging ---
  - CKV_AWS_91   # ALB access logging (requires dedicated S3 bucket)
  - CKV_AWS_18   # S3 state bucket access logging (bootstrap bucket, low risk)
  # --- S3 advanced features (overkill for state bucket) ---
  - CKV_AWS_144  # S3 cross-region replication (single-region deployment)
  - CKV2_AWS_62  # S3 event notifications (not needed for state bucket)
  - CKV2_AWS_61  # S3 lifecycle configuration (versioning handles state history)
  # --- IAM: GitHub Actions deploy role ---
  - CKV_AWS_290  # IAM write access constraints (ECR push + ECS deploy require it)
  - CKV_AWS_355  # IAM wildcard resource (ecr:GetAuthorizationToken requires Resource: *)
  # --- K8s image digest (using tag-based deployment for readability) ---
  - CKV_K8S_43   # Image should use digest (tag-based with immutable ECR tags)
  # --- RDS advanced features ---
  - CKV2_AWS_30  # RDS query logging (log_statement via parameter group, out of scope)
